version: "3"

services:
  ogetc:
    image: ogetclab/ogetc:latest
    command: nodeos --data-dir /opt/ogetc/data --config-dir /opt/ogetc/config
    hostname: ogetc
    ports:
      - 8888:8888
      - 9876:9876
    volumes:
      - /data/ogetc/testnet/data:/opt/ogetc/data
      - /data/ogetc/testnet/config:/opt/ogetc/config